### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by jobveldhuis** [thanethomson/httpwatcher#10]
Hi there, @thanethomson. I am building a static site generator and have decided some time ago that I was going to use your module to create live reloading. However, I see that this module has not been maintained for quite some time. Is there any reason for this? Are you still thinking about supporting this, or would you recommend forking and making necessary changes?

**Comment by thanethomson** [comment]
For now I'd recommend forking. Unfortunately life's been far busier than anticipated and haven't gotten round to tending to my side projects for some time now :disappointed: 

Hopefully that'll change sometime in the next few months :crossed_fingers:

**Comment by jobveldhuis** [comment]
Thanks for your response, @thanethomson. If you'd like, I could help you out maintaining this repo, at least until you are back. I could either fix some of the current issues and shoot in some PRs or help you by maintaining the project directly as collaborator. Let me know what you think, otherwise: feel free to close this issue :)
