### ISSUE TITLE
LiveReload doesn't work at port-forwarding environment.

### ISSUE THREAD

**Issue by ydo-kimura** [thanethomson/httpwatcher#5]
LiveReload doesn't work at port-forwarding environment (e.g. docker container).
It's because host address and port are written in script tags for live reloading.

**Comment by jobveldhuis** [comment]
I will be looking into your PR later today. Thanks for submitting an issue.

**Comment by jobveldhuis** [comment]
This is now available on the `dev` branch and will become available in main and the packaging index with the next release. Thanks for your report!
